name: jksb

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Cherkout
      uses: actions/checkout@v2

    - name: Install firefox and packages
      run: |
        sudo apt-get update -y
        sudo apt-get -y install firefox
        pip install -r requirements.txt

    - name: jksb
      env:
        NETID: ${{secrets.NETID}}
        PASSWORD: ${{secrets.PASSWORD}}
        RECURL: ${{secrets.RECURL}}
        SEND_KEY: ${{secrets.SEND_KEY}}
      run: python jksb_sysu.py
