name: jksb

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Cherkout
      uses: actions/checkout@v2

    - name: Install firefox and packages
      run: |
        sudo apt-get update -y
        sudo apt-get -y install firefox
        pip install -r requirements.txt

    - name: jksb
      env:
        NETID: ${{secrets.NETID}}
        PASSWORD: ${{secrets.PASSWORD}}
        RECURL: ${{secrets.RECURL}}
        SEND_KEY: ${{secrets.SEND_KEY}}
      run: python jksb_sysu.py
